2024-07-14 15:52:55,555 [55152:Thread-3 (process_request_thread)] [app.py:app:page_not_found] [ERROR]: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2024-07-14 15:53:05,192 [55492:Thread-18 (process_request_thread)] [app.py:app:page_not_found] [ERROR]: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2024-07-14 15:53:09,644 [55672:Thread-19 (process_request_thread)] [app.py:app:page_not_found] [ERROR]: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2024-07-14 15:53:12,941 [55832:Thread-33 (process_request_thread)] [app.py:app:page_not_found] [ERROR]: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2024-07-14 15:54:24,492 [53264:Thread-67 (process_request_thread)] [db.py:db:select_all_materials] [ERROR]: (1146, "Table 'test.materialinfo' doesn't exist")
Traceback (most recent call last):
  File "F:\Files\Projects\GitHub\wms-master\falask_Pj\db.py", line 981, in select_all_materials
    cursor.execute("select materialCode,materialName,materialType,inventoryNum,unit,price,inventoryMoney,supplierCode,remark from materialInfo;")
  File "F:\Files\Tools\Python\Python312\Lib\site-packages\pymysql\cursors.py", line 153, in execute
    result = self._query(query)
             ^^^^^^^^^^^^^^^^^^
  File "F:\Files\Tools\Python\Python312\Lib\site-packages\pymysql\cursors.py", line 322, in _query
    conn.query(q)
  File "F:\Files\Tools\Python\Python312\Lib\site-packages\pymysql\connections.py", line 563, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Files\Tools\Python\Python312\Lib\site-packages\pymysql\connections.py", line 825, in _read_query_result
    result.read()
  File "F:\Files\Tools\Python\Python312\Lib\site-packages\pymysql\connections.py", line 1199, in read
    first_packet = self.connection._read_packet()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Files\Tools\Python\Python312\Lib\site-packages\pymysql\connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "F:\Files\Tools\Python\Python312\Lib\site-packages\pymysql\protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "F:\Files\Tools\Python\Python312\Lib\site-packages\pymysql\err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1146, "Table 'test.materialinfo' doesn't exist")
